name: CI

on:
  push:
    branches:
        -bc/ruff-ci
  pull_request:
    branches:
      - main
      - feat*
      - dev*
      - release*

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -e .[linters] --no-cache-dir
      - name: Run linters
        run: ruff . && codespell .

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Setup Bonsai
        working-directory: .bonsai
        run: .\Setup.ps1

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -e .[docs] -e .[aind-data-schema-mapper] --no-cache-dir
      - name: Run tests and coverage
        run: python -m unittest
