name: CI

on:
  push:
    branches:
        - bc/ruff-ci
        - release*
  pull_request:
    branches:
      - main
      - feat*
      - dev*
      - release*

jobs:
  linters:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -e .[linters] --no-cache-dir
      - name: Run ruff format
        run: ruff format .
      - name: Run ruff check
        run: ruff check .
      - name: Run codespell
        run : codespell .

  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.x
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Setup Bonsai
        working-directory: bonsai
        run: .\Setup.ps1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -e .[aind-data-schema-mapper] --no-cache-dir
      - name: Run tests
        run: python -m unittest
      - name: Regenerate schemas
        run: python .\scripts\regenerate.py
      - name: Check for uncommitted changes
        run: git config --global core.safecrlf false && git diff
